# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accountdescription',
            field=models.CharField(default='', max_length=200),
        ),
    ]
