# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='debt',
            field=models.IntegerField(default=0),
        ),
    ]
