# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190211_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downliner',
            old_name='april',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='downliner',
            old_name='upliner',
            new_name='myupliner',
        ),
        migrations.RemoveField(
            model_name='downliner',
            name='august',
        ),
        migrations.RemoveField(
            model_name='downliner',
            name='december',
        ),
        migrations.RemoveField(
            model_name='downliner',
            name='february',
        ),
        migrations.RemoveField(
            model_name='downliner',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='downliner',
            name='january',
        ),
        migrations.RemoveField(
            model_name='downliner',
            name='july',
        ),
        migrations.RemoveField(
            model_name='downliner',
            name='june',
        ),
        migrations.RemoveField(
            model_name='downliner',
            name='march',
        ),
        migrations.RemoveField(
            model_name='downliner',
            name='may',
        ),
        migrations.RemoveField(
            model_name='downliner',
            name='november',
        ),
        migrations.RemoveField(
            model_name='downliner',
            name='october',
        ),
        migrations.RemoveField(
            model_name='downliner',
            name='september',
        ),
        migrations.AddField(
            model_name='downliner',
            name='generation',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='downliner',
            name='month',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='downliner',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
