# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_downliner_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downliner',
            old_name='name',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='downliner',
            name='username',
            field=models.CharField(default='', max_length=250),
        ),
    ]
