# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_downliner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downliner',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
