# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190211_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downliner',
            name='myupliner',
        ),
        migrations.RemoveField(
            model_name='downliner',
            name='user',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='account',
            new_name='fifth',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='member',
            new_name='fifthmth',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='firstmth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fistgen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fouthgen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fouthmth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondgen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondmth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sixthmth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thirdgen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thirdmth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uplinerphone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accountdescription',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Downliner',
        ),
    ]
