# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190212_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='fullname',
        ),
    ]
