# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190212_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fifth',
            new_name='fifthgenb',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='fifthmth',
            new_name='fifthgenr',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='firstmth',
            new_name='fifthmthb',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='fistgen',
            new_name='fifthmthr',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='fouthgen',
            new_name='firstmthb',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='fouthmth',
            new_name='firstmthr',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='secondgen',
            new_name='fistgenb',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='secondmth',
            new_name='fistgenr',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='sixthmth',
            new_name='fouthgenb',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='thirdgen',
            new_name='fouthgenr',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='thirdmth',
            new_name='fouthmthb',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='total',
            new_name='fouthmthr',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondgenb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondgenr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondmthb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondmthr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sixthmthb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sixthmthr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thirdgenb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thirdgenr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thirdmthb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thirdmthr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totalb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totalr',
            field=models.IntegerField(default=0),
        ),
    ]
