# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20190212_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fistgenb',
            new_name='firstgenb',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='fistgenr',
            new_name='firstgenr',
        ),
    ]
