# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-04 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_post2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post2',
            name='subtitle',
            field=models.CharField(default='', max_length=120),
        ),
    ]
