# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-06 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_post3_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('Proffession', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('subtitle', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='post3',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
