# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-08 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_category_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post2',
            name='category',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='Post2',
        ),
    ]
