# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-08 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Item'},
        ),
    ]
