# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-08 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20180108_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
