# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-08 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
