# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-11 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20180110_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='Subtitle',
            new_name='subtitle',
        ),
        migrations.AddField(
            model_name='classes',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
