# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-13 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20180111_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classes',
            name='width_field',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='classes',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
    ]
