# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-14 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20180113_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subtitle',
            field=models.CharField(default='Introduction to GIS', max_length=120),
        ),
        migrations.AlterField(
            model_name='classes',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
