# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-15 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20180115_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
