# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-12 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20180115_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='post4',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post4',
            name='region',
            field=models.CharField(default='', max_length=100),
        ),
    ]
