# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20180215_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='post4',
            name='Jina',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post4',
            name='Simu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post4',
            name='Tukusaidiaje',
            field=models.TextField(default=1, verbose_name='Namba yangu ya uanachama ni..'),
            preserve_default=False,
        ),
    ]
