# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20180220_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post4',
            name='Tukusaidiaje',
        ),
    ]
