# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_post4_tukusaidiaje'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='classes',
            new_name='Downliner',
        ),
    ]
