# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20181221_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downliner',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='downliner',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
