# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='author_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_author',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='item',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
