# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_itemhimaya'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryHimaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.AlterModelOptions(
            name='itemhimaya',
            options={'verbose_name_plural': 'Himaya'},
        ),
        migrations.AlterField(
            model_name='itemhimaya',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CategoryHimaya'),
        ),
    ]
