# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20190209_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryhimaya',
            options={'verbose_name_plural': 'Category Himaya'},
        ),
        migrations.AlterModelOptions(
            name='itemhimaya',
            options={'verbose_name_plural': 'Item Himaya'},
        ),
        migrations.AlterField(
            model_name='itemhimaya',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Categoryhimaya'),
        ),
    ]
