# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20190210_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemhimaya',
            name='author',
        ),
        migrations.RemoveField(
            model_name='itemhimaya',
            name='author_description',
        ),
        migrations.AlterField(
            model_name='itemhimaya',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Categoryhimaya'),
        ),
    ]
