# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20190210_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemhimaya',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryHimaya',
        ),
        migrations.DeleteModel(
            name='ItemHimaya',
        ),
    ]
