# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('himaya', '0002_auto_20190210_1027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Himaya',
            new_name='Item',
        ),
    ]
